/**
 * @file can_bus.c
 *
 * @brief This source file was generated by cantools version 41.0.2 Sun Jan 25 22:18:49 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "can_bus.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int can_bus_obc_heartbeat_pack(
    uint8_t *dst_p,
    const struct can_bus_obc_heartbeat_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u32(src_p->uptime_ms, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->uptime_ms, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->uptime_ms, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->uptime_ms, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->mode, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->error_flags, 0u, 0xffu);

    return (6);
}

int can_bus_obc_heartbeat_unpack(
    struct can_bus_obc_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->uptime_ms = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->mode = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->error_flags = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int can_bus_obc_heartbeat_init(struct can_bus_obc_heartbeat_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_bus_obc_heartbeat_t));

    return 0;
}

uint32_t can_bus_obc_heartbeat_uptime_ms_encode(double value)
{
    return (uint32_t)(value);
}

double can_bus_obc_heartbeat_uptime_ms_decode(uint32_t value)
{
    return ((double)value);
}

bool can_bus_obc_heartbeat_uptime_ms_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint8_t can_bus_obc_heartbeat_mode_encode(double value)
{
    return (uint8_t)(value);
}

double can_bus_obc_heartbeat_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool can_bus_obc_heartbeat_mode_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_bus_obc_heartbeat_error_flags_encode(double value)
{
    return (uint8_t)(value);
}

double can_bus_obc_heartbeat_error_flags_decode(uint8_t value)
{
    return ((double)value);
}

bool can_bus_obc_heartbeat_error_flags_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_bus_obc_mode_cmd_pack(
    uint8_t *dst_p,
    const struct can_bus_obc_mode_cmd_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->mode, 0u, 0xffu);

    return (1);
}

int can_bus_obc_mode_cmd_unpack(
    struct can_bus_obc_mode_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->mode = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int can_bus_obc_mode_cmd_init(struct can_bus_obc_mode_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_bus_obc_mode_cmd_t));

    return 0;
}

uint8_t can_bus_obc_mode_cmd_mode_encode(double value)
{
    return (uint8_t)(value);
}

double can_bus_obc_mode_cmd_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool can_bus_obc_mode_cmd_mode_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_bus_obc_eps_cmd_pack(
    uint8_t *dst_p,
    const struct can_bus_obc_eps_cmd_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->command, 0u, 0xffu);

    return (1);
}

int can_bus_obc_eps_cmd_unpack(
    struct can_bus_obc_eps_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->command = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int can_bus_obc_eps_cmd_init(struct can_bus_obc_eps_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_bus_obc_eps_cmd_t));

    return 0;
}

uint8_t can_bus_obc_eps_cmd_command_encode(double value)
{
    return (uint8_t)(value);
}

double can_bus_obc_eps_cmd_command_decode(uint8_t value)
{
    return ((double)value);
}

bool can_bus_obc_eps_cmd_command_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_bus_obc_adcs_cmd_pack(
    uint8_t *dst_p,
    const struct can_bus_obc_adcs_cmd_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->command, 0u, 0xffu);

    return (1);
}

int can_bus_obc_adcs_cmd_unpack(
    struct can_bus_obc_adcs_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->command = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int can_bus_obc_adcs_cmd_init(struct can_bus_obc_adcs_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_bus_obc_adcs_cmd_t));

    return 0;
}

uint8_t can_bus_obc_adcs_cmd_command_encode(double value)
{
    return (uint8_t)(value);
}

double can_bus_obc_adcs_cmd_command_decode(uint8_t value)
{
    return ((double)value);
}

bool can_bus_obc_adcs_cmd_command_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_bus_eps_heartbeat_pack(
    uint8_t *dst_p,
    const struct can_bus_eps_heartbeat_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u32(src_p->uptime_ms, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->uptime_ms, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->uptime_ms, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->uptime_ms, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->error_flags, 0u, 0xffu);

    return (5);
}

int can_bus_eps_heartbeat_unpack(
    struct can_bus_eps_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->uptime_ms = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->error_flags = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int can_bus_eps_heartbeat_init(struct can_bus_eps_heartbeat_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_bus_eps_heartbeat_t));

    return 0;
}

uint32_t can_bus_eps_heartbeat_uptime_ms_encode(double value)
{
    return (uint32_t)(value);
}

double can_bus_eps_heartbeat_uptime_ms_decode(uint32_t value)
{
    return ((double)value);
}

bool can_bus_eps_heartbeat_uptime_ms_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint8_t can_bus_eps_heartbeat_error_flags_encode(double value)
{
    return (uint8_t)(value);
}

double can_bus_eps_heartbeat_error_flags_decode(uint8_t value)
{
    return ((double)value);
}

bool can_bus_eps_heartbeat_error_flags_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_bus_eps_status_pack(
    uint8_t *dst_p,
    const struct can_bus_eps_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->bus_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->bus_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->bus_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->bus_current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->power, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->power, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->load_status, 0u, 0xffu);

    return (8);
}

int can_bus_eps_status_unpack(
    struct can_bus_eps_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bus_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->bus_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->bus_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->bus_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->power = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->power |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->load_status = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int can_bus_eps_status_init(struct can_bus_eps_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_bus_eps_status_t));

    return 0;
}

uint16_t can_bus_eps_status_bus_voltage_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double can_bus_eps_status_bus_voltage_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool can_bus_eps_status_bus_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t can_bus_eps_status_bus_current_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double can_bus_eps_status_bus_current_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool can_bus_eps_status_bus_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t can_bus_eps_status_power_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double can_bus_eps_status_power_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool can_bus_eps_status_power_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t can_bus_eps_status_load_status_encode(double value)
{
    return (uint8_t)(value);
}

double can_bus_eps_status_load_status_decode(uint8_t value)
{
    return ((double)value);
}

bool can_bus_eps_status_load_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_bus_adcs_heartbeat_pack(
    uint8_t *dst_p,
    const struct can_bus_adcs_heartbeat_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u32(src_p->uptime_ms, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->uptime_ms, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->uptime_ms, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->uptime_ms, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->mode, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->error_flags, 0u, 0xffu);

    return (6);
}

int can_bus_adcs_heartbeat_unpack(
    struct can_bus_adcs_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->uptime_ms = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->mode = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->error_flags = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int can_bus_adcs_heartbeat_init(struct can_bus_adcs_heartbeat_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_bus_adcs_heartbeat_t));

    return 0;
}

uint32_t can_bus_adcs_heartbeat_uptime_ms_encode(double value)
{
    return (uint32_t)(value);
}

double can_bus_adcs_heartbeat_uptime_ms_decode(uint32_t value)
{
    return ((double)value);
}

bool can_bus_adcs_heartbeat_uptime_ms_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint8_t can_bus_adcs_heartbeat_mode_encode(double value)
{
    return (uint8_t)(value);
}

double can_bus_adcs_heartbeat_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool can_bus_adcs_heartbeat_mode_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_bus_adcs_heartbeat_error_flags_encode(double value)
{
    return (uint8_t)(value);
}

double can_bus_adcs_heartbeat_error_flags_decode(uint8_t value)
{
    return ((double)value);
}

bool can_bus_adcs_heartbeat_error_flags_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_bus_adcs_motor_cmd_pack(
    uint8_t *dst_p,
    const struct can_bus_adcs_motor_cmd_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u16(src_p->duty_cycle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->duty_cycle, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->enable, 0u, 0xffu);

    return (3);
}

int can_bus_adcs_motor_cmd_unpack(
    struct can_bus_adcs_motor_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->duty_cycle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->duty_cycle |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->enable = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int can_bus_adcs_motor_cmd_init(struct can_bus_adcs_motor_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_bus_adcs_motor_cmd_t));

    return 0;
}

uint16_t can_bus_adcs_motor_cmd_duty_cycle_encode(double value)
{
    return (uint16_t)(value);
}

double can_bus_adcs_motor_cmd_duty_cycle_decode(uint16_t value)
{
    return ((double)value);
}

bool can_bus_adcs_motor_cmd_duty_cycle_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t can_bus_adcs_motor_cmd_enable_encode(double value)
{
    return (uint8_t)(value);
}

double can_bus_adcs_motor_cmd_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool can_bus_adcs_motor_cmd_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int can_bus_adcs_motor_status_pack(
    uint8_t *dst_p,
    const struct can_bus_adcs_motor_status_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->fault, 0u, 0xffu);

    return (5);
}

int can_bus_adcs_motor_status_unpack(
    struct can_bus_adcs_motor_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->fault = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int can_bus_adcs_motor_status_init(struct can_bus_adcs_motor_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_bus_adcs_motor_status_t));

    return 0;
}

uint16_t can_bus_adcs_motor_status_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double can_bus_adcs_motor_status_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool can_bus_adcs_motor_status_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t can_bus_adcs_motor_status_current_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double can_bus_adcs_motor_status_current_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool can_bus_adcs_motor_status_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t can_bus_adcs_motor_status_fault_encode(double value)
{
    return (uint8_t)(value);
}

double can_bus_adcs_motor_status_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool can_bus_adcs_motor_status_fault_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_bus_adcs_att_est_pack(
    uint8_t *dst_p,
    const struct can_bus_adcs_att_est_t *src_p,
    size_t size)
{
    uint16_t pitch;
    uint16_t roll;
    uint16_t yaw;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    roll = (uint16_t)src_p->roll;
    dst_p[0] |= pack_left_shift_u16(roll, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(roll, 8u, 0xffu);
    pitch = (uint16_t)src_p->pitch;
    dst_p[2] |= pack_left_shift_u16(pitch, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(pitch, 8u, 0xffu);
    yaw = (uint16_t)src_p->yaw;
    dst_p[4] |= pack_left_shift_u16(yaw, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(yaw, 8u, 0xffu);

    return (6);
}

int can_bus_adcs_att_est_unpack(
    struct can_bus_adcs_att_est_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t pitch;
    uint16_t roll;
    uint16_t yaw;

    if (size < 6u) {
        return (-EINVAL);
    }

    roll = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    roll |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->roll = (int16_t)roll;
    pitch = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    pitch |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->pitch = (int16_t)pitch;
    yaw = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    yaw |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->yaw = (int16_t)yaw;

    return (0);
}

int can_bus_adcs_att_est_init(struct can_bus_adcs_att_est_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_bus_adcs_att_est_t));

    return 0;
}

int16_t can_bus_adcs_att_est_roll_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double can_bus_adcs_att_est_roll_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool can_bus_adcs_att_est_roll_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t can_bus_adcs_att_est_pitch_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double can_bus_adcs_att_est_pitch_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool can_bus_adcs_att_est_pitch_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t can_bus_adcs_att_est_yaw_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double can_bus_adcs_att_est_yaw_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool can_bus_adcs_att_est_yaw_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int can_bus_adcs_imu_accel_pack(
    uint8_t *dst_p,
    const struct can_bus_adcs_imu_accel_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    accel_x = (uint16_t)src_p->accel_x;
    dst_p[0] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[2] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[4] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(accel_z, 8u, 0xffu);

    return (6);
}

int can_bus_adcs_imu_accel_unpack(
    struct can_bus_adcs_imu_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;

    return (0);
}

int can_bus_adcs_imu_accel_init(struct can_bus_adcs_imu_accel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_bus_adcs_imu_accel_t));

    return 0;
}

int16_t can_bus_adcs_imu_accel_accel_x_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double can_bus_adcs_imu_accel_accel_x_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool can_bus_adcs_imu_accel_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t can_bus_adcs_imu_accel_accel_y_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double can_bus_adcs_imu_accel_accel_y_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool can_bus_adcs_imu_accel_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t can_bus_adcs_imu_accel_accel_z_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double can_bus_adcs_imu_accel_accel_z_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool can_bus_adcs_imu_accel_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int can_bus_adcs_imu_gyro_pack(
    uint8_t *dst_p,
    const struct can_bus_adcs_imu_gyro_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[0] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[2] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[4] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);

    return (6);
}

int can_bus_adcs_imu_gyro_unpack(
    struct can_bus_adcs_imu_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    gyro_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;

    return (0);
}

int can_bus_adcs_imu_gyro_init(struct can_bus_adcs_imu_gyro_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_bus_adcs_imu_gyro_t));

    return 0;
}

int16_t can_bus_adcs_imu_gyro_gyro_x_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double can_bus_adcs_imu_gyro_gyro_x_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool can_bus_adcs_imu_gyro_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t can_bus_adcs_imu_gyro_gyro_y_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double can_bus_adcs_imu_gyro_gyro_y_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool can_bus_adcs_imu_gyro_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t can_bus_adcs_imu_gyro_gyro_z_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double can_bus_adcs_imu_gyro_gyro_z_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool can_bus_adcs_imu_gyro_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}
